/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "confirmation": {
        "changedStatus": string;
        "editedSuccess": string;
        "registerSuccess": string;
        "loginSuccess": string;
    };
    "exception": {
        "emailExist": string;
        "UserAlready": string;
        "UserNotFound": string;
        "UserIsInactive": string;
        "IncorrectPassword": string;
    };
    "validation": {
        "invalidDate": string;
        "isNotEmpty": string;
        "invalidNumber": string;
        "isNotEmptySizeClothing": string;
        "isNotEmptyNumberClothing": string;
        "isNotEmptyDescClothing": string;
        "IsNotEmptyUserName": string;
        "IsNotEmptyUserEmail": string;
        "IsNotEmptyUserEnrollment": string;
        "IsNotEmptyUserRole": string;
        "IsNotEmptyPermissionAdmin": string;
        "IsNotEmptyPermissionStock": string;
        "IsNotEmptyPermissionWashing": string;
        "IsNotEmptyPermissionOperator": string;
        "NameMaxLength": string;
        "invalidLocalizationLength": string;
        "invalidPositionLength": string;
        "HasNoPermissions": string;
        "teste": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
